name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PROD_AWS_BUCKET_NAME: ${{ secrets.PROD_AWS_BUCKET_NAME }}
      PROD_AWS_BUCKET_KEY_NAME: ${{ secrets.PROD_AWS_BUCKET_KEY_NAME }}
